Repository w6d-io/x, pull requests merged in 2021-11, with the labels that each got.

#1 [ADD] functions to edit Error struct fields
  errorx/errorx.go
  errorx/errorx_test.go
Labels: enhancement, minor

#2 feat link header
  CHANGELOG.md
  go.sum
  httpx/link_header.go
  httpx/link_header_test.go
Labels: patch

#4 perf: logx: add method field
  CHANGELOG.md
  httpx/httpx.go
  logx/logx.go
Labels: patch

#3 Feat kafkax mongox
  .gitignore
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  kafkax/client_consumer_mock.go
  kafkax/client_producer_mock.go
  kafkax/consumer.go
  kafkax/consumer_test.go
  kafkax/interfaces.go
  kafkax/kafkax.go
  kafkax/kafkax_suite_test.go
  kafkax/options.go
  kafkax/producer.go
  kafkax/producer_test.go
  kafkax/types.go
  mongox/aggregate.go
  mongox/aggregate_test.go
  mongox/bson_mock.go
  mongox/bulk.go
  mongox/bulk_test.go
  mongox/client.go
  mongox/client_mock.go
  mongox/client_test.go
  mongox/codec_proto.go
  mongox/codec_test.go
  mongox/collection_mock.go
  mongox/counter.go
  mongox/counter_test.go
  mongox/create_index.go
  mongox/create_index_test.go
  mongox/cursor_mock.go
  mongox/cursor_mock_test.go
  mongox/delete.go
  mongox/delete_test.go
  mongox/get.go
  mongox/get_test.go
  mongox/index_mock.go
  mongox/insert.go
  mongox/insert_test.go
  mongox/interface.go
  mongox/mongo.go
  mongox/mongo_suite_test.go
  mongox/options.go
  mongox/pipeline.go
  mongox/pipeline_test.go
  mongox/singleresult_mock.go
  mongox/test1.pb_test.go
  mongox/testdata/google/protobuf/timestamp.proto
  mongox/testdata/test1.proto
  mongox/update.go
  mongox/update_test.go
Labels: minor

#6 Feat kafkax mongox
  CHANGELOG.md
  mongox/aggregate_test.go
  mongox/client.go
  mongox/client_mock.go
  mongox/client_test.go
  mongox/counter_test.go
  mongox/create_index_test.go
  mongox/cursor_mock_test.go
  mongox/delete_test.go
  mongox/get_test.go
  mongox/insert_test.go
  mongox/interface.go
  mongox/mongo.go
  mongox/update_test.go
Labels: patch

#7 Chore kafkax
  CHANGELOG.md
  kafkax/client_consumer_mock.go
  kafkax/consumer.go
  kafkax/consumer_test.go
  kafkax/interfaces.go
  kafkax/kafkax.go
  kafkax/producer.go
  kafkax/producer_test.go
  mongox/interface.go
Labels: patch

#9 Clean mongox
  CHANGELOG.md
  mongox/client.go
  mongox/client_test.go
  mongox/interface.go
Labels: patch

#10 Create LICENSE
  LICENSE
Labels: patch

#11 Chore goreport
  CHANGELOG.md
  flagx/flagx.go
Labels: patch

#12 http: fix ip address feature
  CHANGELOG.md
  httpx/httpx.go
Labels: patch

#13 chore: remove header text
  CHANGELOG.md
  cmdx/cmdx_suite_test.go
  cmdx/helper.go
  cmdx/helper_test.go
  cmdx/version.go
  cmdx/version_test.go
  grpcx/grpcx.go
  grpcx/grpcx_suite_test.go
  grpcx/grpcx_test.go
  healthx/healthx.go
  healthx/healthx_suite_test.go
  healthx/healthx_test.go
  httpx/link_header.go
  httpx/link_header_test.go
  kafkax/consumer_test.go
  kafkax/kafkax_suite_test.go
  kafkax/producer_test.go
  logx/doc.go
  mongox/aggregate_test.go
  mongox/client_test.go
  mongox/codec_test.go
  mongox/counter_test.go
  mongox/create_index_test.go
  mongox/cursor_mock_test.go
  mongox/delete_test.go
  mongox/get_test.go
  mongox/insert_test.go
  mongox/mongo_suite_test.go
  mongox/update_test.go
Labels: patch

#14 Clean report
  CHANGELOG.md
  Makefile
  cmdx/helper.go
  errorx/errorx.go
  errorx/errorx_test.go
  flagx/flagx.go
  flagx/flagx_test.go
  grpcx/grpcx.go
  grpcx/grpcx_test.go
  healthx/healthx.go
  httpx/httpx.go
  httpx/httpx_test.go
  kafkax/client_consumer_mock.go
  kafkax/client_producer_mock.go
  kafkax/consumer.go
  kafkax/consumer_test.go
  kafkax/interfaces.go
  kafkax/kafkax.go
  kafkax/options.go
  kafkax/producer.go
  kafkax/types.go
  logx/logx.go
  logx/logx_test.go
  mongox/aggregate.go
  mongox/aggregate_test.go
  mongox/bson_mock.go
  mongox/bulk.go
  mongox/client.go
  mongox/client_mock.go
  mongox/codec_proto.go
  mongox/codec_test.go
  mongox/collection_mock.go
  mongox/counter.go
  mongox/create_index.go
  mongox/cursor_mock.go
  mongox/delete.go
  mongox/get.go
  mongox/index_mock.go
  mongox/insert.go
  mongox/interface.go
  mongox/mongo.go
  mongox/options.go
  mongox/pipeline.go
  mongox/singleresult_mock.go
  mongox/update.go
  pflagx/pflagx.go
  pflagx/pflagx_test.go
Labels: minor

#15 break: p/flagx improve init
  .chglog/config.yml
  CHANGELOG.md
  flagx/flagx.go
  flagx/flagx_test.go
  pflagx/pflagx.go
  pflagx/pflagx_test.go
Labels: minor

#16 chore: httpx: fix misspelling
  CHANGELOG.md
  httpx/link_header.go
Labels: patch
